In [1]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\giuseppe\anaconda3\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import dotenv
import sqlalchemy
import pandas as pd
from sqlalchemy import create_engine
dotenv.load_dotenv(override=True, dotenv_path="C:/Users/Giuseppe/OneDrive/Desktop/DATA ANALYST/3_PYTHON/.env")
username = os.getenv("username")
password = os.getenv("password")
host = os.getenv("host")
dbname = os.getenv("dbname")
conn_string = "mysql+pymysql://" + username + ":" + password + "@" + host + "/" + dbname
db_engine = sqlalchemy.create_engine(conn_string)
conn_string

'mysql+pymysql://studente_dapt:Ep1c0d3!!D4t4**4n4lys1s@epicode-data-pt-mysql.cvetyjye2qbl.eu-central-1.rds.amazonaws.com/AdventureWorksDW'

In [3]:
query = "SELECT * FROM dimproduct"
pd.read_sql(query, db_engine)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
1,2,BA-8327,NaN,None,None,Bearing Ball,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
2,3,BE-2349,NaN,None,None,BB Ball Bearing,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
3,4,BE-2908,NaN,None,None,Headset Ball Bearings,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
4,5,BL-2036,NaN,None,None,Blade,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,602,BB-8107,5.0,G,None,ML Bottom Bracket,Eje de pedalier GM,Axe de pédalier ML,44.95,1,...,铝合金车圈；大直径脚蹬轴。,فناجين من سبيكة الألومنيوم؛ ذات محور دوران كبي...,כיסויים מסגסוגת אלומיניום; ציר רחב-קוטר.,ดุมอลูมิเนียมอัลลอยด์ แกนเพลาขนาดใหญ่,Außenringe aus Aluminiumlegierung; Radachse mi...,アルミニウム合金カップ、大径スピンドル。,Alüminyum alaşımı orta göbekler; geniş çaplı mil.,2013-07-01,NaT,Current
602,603,BB-9108,5.0,G,None,HL Bottom Bracket,Eje de pedalier GA,Axe de pédalier HL,53.94,1,...,铝合金车圈和空心轴。,فناجين من سبيكة الألومنيوم ومحور أجوف.,כיסויים מסגסוגת אלומיניום וציר חלול.,ดุมอลูมิเนียมอัลลอยด์และเพลากลวง,Außenringe aus Aluminiumlegierung und hohle Ac...,アルミニウム合金カップとホロー アクスル。,Alüminyum alaşımı orta göbekler ve içi boş aks.,2013-07-01,NaT,Current
603,604,BK-R19B-44,2.0,LB,CM,"Road-750 Black, 44","Carretera: 750, negra, 44","Vélo de route 750 noir, 44",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current
604,605,BK-R19B-48,2.0,LB,CM,"Road-750 Black, 48","Carretera: 750, negra, 48","Vélo de route 750 noir, 48",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current
605,606,BK-R19B-52,2.0,LB,CM,"Road-750 Black, 52","Carretera: 750, negra, 52","Vélo de route 750 noir, 52",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current

In [4]:
#Esercizio 1/3 Estraioamo la Tabella dimproduct... e valutiamo quanto segue :  #
#•Quanti dati ci sono in totale?
#• Quali sono i metadati?
#• Stampiamo il primo elemento
#• Stampiamo l'ultimo elemento
#• Riusciamo a stampare cinque elementi a caso?
#• Quali sono i colori disponibili?#

In [5]:
import pandas as pd  #Importo la libreria Pandas#

In [6]:
df = pd.read_sql(query, db_engine) #metto in una variabile la mia query della tabella dimproduct#

In [7]:
df.shape #Utilizzo l'attributo shape per conoscere numero di righe e colonne#

(606, 36)

In [8]:
list (df.columns) # utilizzo l'attirbuto columns facendomi restituire della tabella solo intestazione colonna in una lista#

['ProductKey',
 'ProductAlternateKey',
 'ProductSubcategoryKey',
 'WeightUnitMeasureCode',
 'SizeUnitMeasureCode',
 'EnglishProductName',
 'SpanishProductName',
 'FrenchProductName',
 'StandardCost',
 'FinishedGoodsFlag',
 'Color',
 'SafetyStockLevel',
 'ReorderPoint',
 'ListPrice',
 'Size',
 'SizeRange',
 'Weight',
 'DaysToManufacture',
 'ProductLine',
 'DealerPrice',
 'Class',
 'Style',
 'ModelName',
 'LargePhoto',
 'EnglishDescription',
 'FrenchDescription',
 'ChineseDescription',
 'ArabicDescription',
 'HebrewDescription',
 'ThaiDescription',
 'GermanDescription',
 'JapaneseDescription',
 'TurkishDescription',
 'StartDate',
 'EndDate',
 'Status']

In [9]:
df.columns # lo stesso lo potevo ottenere ... ma non in formato lista... utilizzando semplicemetne .columns#

Index(['ProductKey', 'ProductAlternateKey', 'ProductSubcategoryKey',
       'WeightUnitMeasureCode', 'SizeUnitMeasureCode', 'EnglishProductName',
       'SpanishProductName', 'FrenchProductName', 'StandardCost',
       'FinishedGoodsFlag', 'Color', 'SafetyStockLevel', 'ReorderPoint',
       'ListPrice', 'Size', 'SizeRange', 'Weight', 'DaysToManufacture',
       'ProductLine', 'DealerPrice', 'Class', 'Style', 'ModelName',
       'LargePhoto', 'EnglishDescription', 'FrenchDescription',
       'ChineseDescription', 'ArabicDescription', 'HebrewDescription',
       'ThaiDescription', 'GermanDescription', 'JapaneseDescription',
       'TurkishDescription', 'StartDate', 'EndDate', 'Status'],
      dtype='object')

In [10]:
df.head(1) #Per stampare il 1° elemento utilizzo la f(x) head... indicando la 1° riga#

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current

In [11]:
df.tail(1) #Per stampare l'ultima colonna utilizzo la f(x) tail ... attnenziona a non far confusione tra productkey#
# e etichetta tabella che partendo da 0 è 605 ... mentre ProductKey è 606 #

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
605,606,BK-R19B-52,2.0,LB,CM,"Road-750 Black, 52","Carretera: 750, negra, 52","Vélo de route 750 noir, 52",343.65,1,...,入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。,إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...,"אופני מבוגרים למתחילים; מציעים רכיבה נוחה ""מחו...",จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...,Ein Erwachsenenrad für Einsteiger; bietet Komf...,エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...,"""Başlangıç seviyesinde yetişkin bisikleti, kır...",2013-07-01,NaT,Current

In [12]:
df.sample(5) #con la f(x) sample mi restituisce un numero n di righe casuali #

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
452,453,SH-M897-M,22.0,None,None,"Men's Sports Shorts, M","Pantalones cortos de deporte para hombre, M","Cuissards de route pour hommes, taille M",24.75,1,...,男士八拼片竞赛用运动短裤 – 氨纶材质、弹性腰带并带腿夹。,قمصان سباق رجالي ذات ثمانية أقسام، من قماش سبا...,"מכנסי גברים קצרים לתחרויות, 8 חלקים – עשויים ס...",กางเกงแข่ง 8 ช่องสำหรับสุภาพบุรุษ - เส้นใยสแปน...,Rennradhose für Herren - Lycra mit elastischem...,男性用 8 枚剥ぎの競技用ショーツ - 伸縮性のあるウエスト バンドとレッグ グリッパー付き...,Erkekler için 8 parçalı yarış şortu - elastik ...,2012-07-01,2008-12-27,None
327,328,BK-R50R-48,2.0,LB,CM,"Road-650 Red, 48","Carretera: 650, roja, 48","Vélo de route 650 rouge, 48",413.15,1,...,此自行车经济实惠，具有我们的高档车型所拥有的许多功能。相同的车灯、刚架以及我们驰名业界的快速...,إنها دراجة ذات سعر مناسب لإمكاناتها كما تتمتع ...,אופניים המהווים תמורה נאותה למחירם ובעלי רבות ...,จักรยานที่ให้ความคุ้มค่า ด้วยคุณสมบัติพิเศษมาก...,"""Kostengünstiges Rad mit vielen Funktionen uns...",最高級モデルの特色の多くを備えた値打ち価格の自転車です。ハイエンド クラスに匹敵する軽量高剛...,Değerine uygun olarak fiyatlandırılan bisiklet...,2011-07-01,2007-12-28,None
129,130,LN-5162,NaN,None,None,Lock Nut 11,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
56,57,HN-1220,NaN,None,None,Hex Nut 17,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
467,468,GL-F110-S,20.0,None,None,"Full-Finger Gloves, S","Guantes completos, P","Gants longs, taille S",15.67,1,...,合成材质手掌、灵活的指关节、上部带有透气型网眼。AWC车队赛手专用。,قفاز ذو راحة يد صناعية، ومفاصل أصابع مرنة، وفت...,"אזור כף יד מחומר סינטטי, מפרקים גמישים, רשת נו...",แผ่นฝ่ามือสังเคราะห์ ข้อนิ้วยืดหยุ่น และตาข่าย...,"""Ballenschutz Synthetik, flexible Fingerpartie...",シンセティック レザーの手のひら部分、柔軟性のある関節部分、通気性のあるメッシュの甲部分。A...,"""Sentetik avuç içi, esnek parmaklar, üst taraf...",2012-07-01,2008-12-27,None

In [13]:
df['Color'].unique() #Indico la colonna che mi interessa... e con la f(x) unique() chiedo di restituirmi i valori unici della#
#colonna#

array(['NA', 'Black', 'Silver', 'Red', 'White', 'Blue', 'Multi', 'Yellow',
       'Grey', 'Silver/Black'], dtype=object)

In [14]:
#Esercizio 2/3 
#• In media quanto pesano i prodotti?
#• Quanto pesa il più leggero?
#• Quanto pesa il più pesante?
#• Quanti prodotti pesano più di 100 Kg?
#• Quanto costano in media i prodotti (colonna DealerPrice)?
#• Se prendiamo un quarto di tutti i prodotti, in modo che siano i più costosi,
#quale sarà il loro range di prezzo?#

In [15]:
df['Weight'].describe() # con la semplice descrizione della colonna per parametri statistici usando la f(x)#
#describe ... rispondiamo alle prime 3 domande#

count     282.000000
mean       56.193227
std       158.000652
min         2.120000
25%         2.680000
50%        15.420000
75%        24.130000
max      1050.000000
Name: Weight, dtype: float64

In [16]:
w=df.loc[:,'Weight']>100 #Per conoscere il numero dei prodotti che pesano più di 100 kg. faccio un filtro e lo metto in#
#una variabile w #

In [17]:
df.loc[w] # in questo modo mi stampo solo le righe dove i prodotti pesano più di 100 kg.

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
179,180,RM-M464,NaN,G,None,LL Mountain Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
180,181,RM-M692,NaN,G,None,ML Mountain Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
181,182,RM-M823,NaN,G,None,HL Mountain Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
182,183,RM-R436,NaN,G,None,LL Road Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
183,184,RM-R600,NaN,G,None,ML Road Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
184,185,RM-R800,NaN,G,None,HL Road Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
185,186,RM-T801,NaN,G,None,Touring Rim,,,NaN,0,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
412,413,FW-R623,17.0,G,None,LL Road Front Wheel,Rueda de carretera delantera GB,Roue avant de vélo de route LL,37.99,1,...,适用于入门级骑乘者的公路型备用前轮。,عجلة طريق أمامية بديلة لقائدي الدراجات المبتدئين.,גלגל חלופי קדמי לרכיבת כביש לרוכב המתחיל.,ล้อหน้าจักรยานภูเขาอะไหล่สำหรับนักปั่นระดับเริ...,Ersatzvorderrad für Einsteiger.,初心者向けの交換用フロント ロード ホイール。,Başlangıç seviyesindeki sürücüler için yedek ö...,2012-07-01,2008-12-27,None
413,414,FW-R762,17.0,G,None,ML Road Front Wheel,Rueda de carretera delantera GM,Roue avant de vélo de route ML,110.28,1,...,坚固的合金具有快拆式车毂。,تتميز بوجود سبيكة قوية تحتوي على محور عجلة سري...,סגסוגת איתנה מאפיינת את מנגנון השחרור המהיר של...,ดุมล้ออัลลอยด์ที่ทนทาน ถอดได้อย่างรวดเร็ว,Robustes Design mit Schnellspann-Nabe.,頑丈な合金による、クイックリリース ハブ。,"""Dayanıklı alaşım, kolay sökülebilen göbek içe...",2012-07-01,2008-12-27,None
414,415,FW-R820,17.0,G,None,HL Road Front Wheel,Rueda de carretera delantera GA,Roue avant de vélo de route HL,146.55,1,...,具有双层轮缘的坚固车轮。,عجلة قوية بإطار معدني ذي طبقتين.,גלגל חזק עם חישוק בעל הלחמה כפולה.,ล้อที่แข็งแกร่งพร้อมขอบล้อผนังสองชั้น,Starkes Rad mit doppelt beschichteter Felge.,ダブルウォール リムを持つ頑丈なホイール。,İki duvarlı jantlı güçlü tekerlek.,2012-07-01,2008-12-27,None
421,422,RW-R623,17.0,G,None,LL Road Rear Wheel,Rueda de carretera trasera GB,Roue arrière de vélo de route LL,49.98,1,...,适用于入门级骑乘者的公路型备用前轮。,عجلة طريق أمامية بديلة لقائدي الدراجات المبتدئين.,גלגל חלופי קדמי לרכיבת כביש לרוכב המתחיל.,ล้อหน้าจักรยานภูเขาอะไหล่สำหรับนักปั่นระดับเริ...,Ersatzhinterrad für Einsteiger.,初心者向けの交換用リア ロード ホイール。,Başlangıç seviyesinde sürücüler için yedek ark...,2012-07-01,2008-12-27,None
422,423,RW-R762,17.0,G,None,ML Road Rear Wheel,Rueda de carretera trasera GM,Roue arrière de vélo de route ML,122.27,1,...,带不锈钢辐条的铝合金轮缘；特别为提速而设计。,إطار معدني مصنوع من سبيكة الألومنيوم بقضبان شع...,חישוק מסגסוגת אלומיניום עם חישורים מפלדת אל-חל...,ขอบอลูมิเนียมอัลลอยด์พร้อมซี่ล้อสเตนเลส สำหรับ...,Felge aus Aluminiumlegierung mit Speichen aus ...,高速走行用のステンレス製スポークを備えたアルミニウム合金リム。,Paslanmaz çelik telli alüminyum alaşımı jantla...,2012-07-01,2008-12-27,None
423,424,RW-R820,17.0,G,None,HL Road Rear Wheel,Rueda de carretera trasera GA,Roue arrière de vélo de route HL,158.53,1,...,具有双层轮缘的坚固后轮。,عجلة خلفية قوية بإطار معدني ذي طبقتين.,גלגל אחורי חזק עם חישוק בעל הלחמה כפולה.,ล้อหลังที่แข็งแกร่งพร้อมขอบล้อผนังสองชั้น,Starkes Hinterrad mit doppelt beschichteter Fe...,ダブルウォール リムを持つ頑丈なリア ホイール。,İki duvarlı jantlı güçlü arka tekerlek.,2012-07-01,2008-12-27,None
500,501,RD-2308,9.0,G,None,Rear Derailleur,Desviador trasero,Dérailleur arrière,53.93,1,...,宽连杆设计。,تصميم عريض الوصلات.,עיצוב רחב-חוליות.,การออกแบบให้มีจุดเชื่อมกว้าง,Wide-Link-Design.,ワイドリンク デザイン。,Geniş bağlantılı tasarım.,2013-07-01,NaT,Current
513,514,RB-9231,6.0,G,None,Rear Brakes,Frenos traseros,Freins arrière,47.29,1,...,None,None,None,None,None,None,None,2013-07-01,NaT,Current
541,542,PD-M282,13.0,G,None,LL Mountain Pedal,Pedal de montaña GB,Pédale de VTT LL,17.98,1,...,展开式踏板便于您穿任何鞋子骑乘；适用于各种情况。,هيكل أساسي واسع بحيث يمكنك القيادة بأي حذاء، و...,משטח דוושות מורחב המתאים לרכיבה בכל סוגי הנעלי...,คันถีบขนาดใหญ่ สำหรับการขับขี่ด้วยรองเท้าชนิดใ...,Größere Fläche für Komfort in allen Schuhen.,靴を選ばない拡張プラットフォームなので、オールラウンド ライディングに最適です。,"""Geniş pedalı sayesinde her tür ayakkabıyla sü...",2013-07-01,NaT,Current
542,543,PD-M340,13.0,G,None,ML Mountain Pedal,Pedal de montaña GM,Pédale de VTT ML,27.57,1,...,无扣带式脚踏轻型耐用且松紧可调。,دواسة خفيفة الوزن شديدة التحمّل بلا مشابك وذات...,דוושה עמידה נטולת חבקים עם מאמץ מתכוונן.,คันถีบน้ำหนักเบา ทนทาน ไม่มีคลิป และสามารถปรับ...,Leichte Pedale ohne Pedalhaken mit anpassbarer...,軽量で耐久性に優れ、テンション調整が可能なクリップレス ペダル。,"""Hafif, dayanıklı klipssiz pedal, gerginliği a...",2013-07-01,NaT,Current
543,544,PD-M562,13.0,G,None,HL Mountain Pedal,Pedal de montaña GA,Pédale de VTT HL,35.96,1,...,不锈钢材质；易于去泥。,مصنوعة من الفولاذ الذي لا يصدأ، والذي تم تصميم...,פלדת אל-חלד; עיצוב המשיר בוץ בקלות.,โลหะสเตนเลส ได้รับการออกแบบให้สลัดโคลนออกได้ง่าย,Edelstahl; schmutzabweisendes Design.,ステンレス製で、泥を簡単に払い落せるデザインです。,"""Paslanmaz çelik, çamuru üzerinden kolayca ata...",2013-07-01,NaT,Current
544,545,PD-R347,13.0,G,None,LL Road Pedal,Pedal de carretera GB,Pédale de vélo de route LL,17.98,1,...,无扣带式脚踏 – 铝制。,دواستان بلا مشابك مصنوعتان من الألومنيوم.,דוושות ללא חבקים – אלומיניום.,คันถีบไม่มีคลิป - อลูมิเนียม,Pedale ohne Pedalhaken - Aluminium.,クリップレス ペダル (アルミニウム)。,Klipssiz pedallar - alüminyum.,2013-07-01,NaT,Current
545,546,PD-R563,13.0,G,None,ML Road Pedal,Pedal de carretera GM,Pédale de vélo de route ML,27.57,1,...,轻型铝合金结构。,تركيبة سبيكة ألومنيوم خفيفة الوزن.,מבנה סגסוגת אלומיניום קל משקל.,โครงสร้างอลูมิเนียมอัลลอยด์น้ำหนักเบา,Leichte Aluminiumlegierung.,軽量アルミニウム合金構造。,Hafif alüminyum alaşımı konstrüksiyon.,2013-07-01,NaT,Current
546,547,PD-R853,13.0,G,None,HL Road Pedal,Pedal de carretera GA,Pédale de vélo de route HL,35.96,1,...,松紧可调的高档无扣带式脚踏。,دواستان من أعلى الطرازات بقوة شدّ يمكن تعديلها.,דוושות נטולות חבקים מהשורה הראשונה עם מאמץ מתכ...,คันถีบระดับเยี่ยม ไม่มีคลิป ปรับความตึงได้,Top-Pedale ohne Pedalhaken mit anpassbarer Spa...,テンション調整が可能な最高級クリップレス ペダル。,Gerginliği ayarlanabilen gerginlikli en üst sı...,2013-07-01,NaT,Current
554,555,FB-9873,6.0,G,None,Front Brakes,Frenos delanteros,Freins avant,47.29,1,...,全天候刹车垫；通过增加与轮缘的接触面积来提供优异的制动功能。,تحتوي على بطانات (تيل) فرامل، تناسب كافة الظرو...,רפידות מעצור המתאימות לכל מזג אוויר; מספקות עצ...,ยางเบรกสำหรับทุกสภาพอากาศ เพื่อการหยุดที่มั่นใ...,Allwetter-Bremsbeläge für erstklassiges Bremse...,全天候型ブレーキ パッドを採用し、リムに広い表面積を適用することにより優れた制動力を提供します。,"""Tüm hava durumlarına uygun fren pedleri, jant...",2013-07-01,NaT,Current
555,556,CS-4759,8.0,G,None,LL Crankset,Bielas GB,Pédalier LL,77.92,1,...,极其坚实的脚踏轴。,محور دوران صلب فائق الأداء.,ציר קשיח במיוחד.,เพลาล้อสุดแกร่ง,Extrem robuste Achse.,最強の剛性を誇るスピンドル。,Çok sağlam mil.,2013-07-01,NaT,Current
556,557,CS-6583,8.0,G,None,ML Crankset,Bielas GM,Pédalier ML,113.88,1,...,高强度的曲臂。,ذراع تدوير شديد القوة.,זרוע ארכובה עתירת עוצמה.,คันบังคับแข็งแรงเป็นพิเศษ,Robuster Pedalarm.,高強度クランク アーム。,Çok güçlü krank kolu.,2013-07-01,NaT,Current
557,558,CS-9183,8.0,G,None,HL Crankset,Bielas GA,Pédalier HL,179.82,1,...,三重齿盘；铝制曲臂；完美变速。,مجموعة تدوير ثلاثية، وذراع تدوير ألومنيوم، وإم...,"ערכת ארכובה משולשת, זרוע ארכובה מאלומיניום, חי...",ชุดควบคุมสามชั้น คันบังคับอลูมิเนียม และการเปล...,Dreifach-Kurbelsatz; Aluminium-Pedalarm; tadel...,トリプル クランクセット、アルミニウム クランク アーム、完璧なシフト。,"""Üçlü ruble, alüminyum krank kolu, takılmadan ...",2013-07-01,NaT,Current
600,601,BB-7421,5.0,G,None,LL Bottom Bracket,Eje de pedalier GB,Axe de pédalier LL,23.97,1,...,铬钢。,الفولاذ الكرومولي,פלדת כרומולי (כרום-מולובדניום),โลหะโครโมลี,Chromstahl.,クロム鋼。,Kromoli çelik.,2013-07-01,NaT,Current
601,602,BB-8107,5.0,G,None,ML Bottom Bracket,Eje de pedalier GM,Axe de pédalier ML,44.95,1,...,铝合金车圈；大直径脚蹬轴。,فناجين من سبيكة الألومنيوم؛ ذات محور دوران كبي...,כיסויים מסגסוגת אלומיניום; ציר רחב-קוטר.,ดุมอลูมิเนียมอัลลอยด์ แกนเพลาขนาดใหญ่,Außenringe aus Aluminiumlegierung; Radachse mi...,アルミニウム合金カップ、大径スピンドル。,Alüminyum alaşımı orta göbekler; geniş çaplı mil.,2013-07-01,NaT,Current
602,603,BB-9108,5.0,G,None,HL Bottom Bracket,Eje de pedalier GA,Axe de pédalier HL,53.94,1,...,铝合金车圈和空心轴。,فناجين من سبيكة الألومنيوم ومحور أجوف.,כיסויים מסגסוגת אלומיניום וציר חלול.,ดุมอลูมิเนียมอัลลอยด์และเพลากลวง,Außenringe aus Aluminiumlegierung und hohle Ac...,アルミニウム合金カップとホロー アクスル。,Alüminyum alaşımı orta göbekler ve içi boş aks.,2013-07-01,NaT,Current

In [18]:
w.value_counts() #Ci sono 28 prodotti che pesano più di 100 Kg.#

Weight
False    578
True      28
Name: count, dtype: int64

In [19]:
df['ListPrice'].describe()#Per prendere il quarto più costoso devo prende della ListPrice il max. quartile#

count     395.000000
mean      747.661544
std       838.708359
min         2.290000
25%        69.990000
50%       364.090000
75%      1204.320000
max      3578.270000
Name: ListPrice, dtype: float64

In [20]:
dp=df.loc[:,'DealerPrice']
dp.describe() #Mi seleziono con .loc la colonna 'DealerPrice' e con describe vedo i dati statistici della colonna#

count     395.000000
mean      448.597060
std       503.225071
min         1.374000
25%        41.994000
50%       218.454000
75%       722.594900
max      2146.962000
Name: DealerPrice, dtype: float64

In [21]:
dp.mean() #Ad ulteriore confema con la f(x) mean mi calcolo la media della colonna che è 448,5970...#

448.5970597468353

In [22]:
#Se prendiamo un quarto di tutti i prodotti, in modo che siano i più costosi,
#quale sarà il loro range di prezzo?#

In [23]:
df['ListPrice'].describe() #Attraverso .describe identifico il3° quartile#

count     395.000000
mean      747.661544
std       838.708359
min         2.290000
25%        69.990000
50%       364.090000
75%      1204.320000
max      3578.270000
Name: ListPrice, dtype: float64

In [24]:
# Mi creo una lista con tutti i valori del 3° quartile cioè quelli > 1.204,32 #
max_quartile = df[df['ListPrice'] > 1204.32]
max_quartile_valori = df[df['ListPrice'] > 1204.32]['ListPrice']
print(max_quartile_valori)

237    1263.46
238    1301.36
239    1431.50
240    1263.46
241    1301.36
        ...
578    1214.85
579    1700.99
580    1700.99
581    1700.99
582    1700.99
Name: ListPrice, Length: 98, dtype: float64

In [25]:
x=max_quartile_valori
x.describe()  # In tal modo mi individuo il min ed il max del 3° quartile#

count      98.000000
mean     1954.733265
std       740.081219
min      1214.850000
25%      1349.600000
50%      1700.990000
75%      2384.070000
max      3578.270000
Name: ListPrice, dtype: float64

In [26]:
range_prezzi = max(x) - min(x)
print(f'Il minimo è :{min(x)}  Il massimo è:, {max(x)}')
print(f"Il range è: {range_prezzi}")  # Mi calcolo il range tra min e max e poi stampo tutto#

Il minimo è :1214.85  Il massimo è:, 3578.27
Il range è: 2363.42

In [27]:
Blue= df.loc[:,'Color']='Blue'

In [28]:
#Dataset : Amazon collegamento #
#Valutiamo la dimensione del dataset#

In [29]:
import pandas as pd
import os
print(os.getcwd())
filepath = "C:/Users/Giuseppe/3_PYTHON/FILE_ESERC_CSV/amazon.csv"
amazon = pd.read_csv(filepath)

C:\Users\Giuseppe\3_PYTHON

In [30]:
amazon = pd.read_csv(filepath)

In [31]:
amazon

                                              reviewText  Positive
0      This is a one of the best apps acording to a b...         1
1      This is a pretty good version of the game for ...         1
2      this is a really cool game. there are a bunch ...         1
3      This is a silly game and can be frustrating, b...         1
4      This is a terrific game on any pad. Hrs of fun...         1
...                                                  ...       ...
19995  this app is fricken stupid.it froze on the kin...         0
19996  Please add me!!!!! I need neighbors! Ginger101...         1
19997  love it!  this game. is awesome. wish it had m...         1
19998  I love love love this app on my side of fashio...         1
19999  This game is a rip off. Here is a list of thin...         0

[20000 rows x 2 columns]

In [32]:
#Valutiamo la dimensione del dataset#

In [33]:
amazon.shape

(20000, 2)

In [34]:
# Visualizziamo dieci righe a caso #

In [35]:
amazon.sample(10)

                                              reviewText  Positive
10261  In my house we play this and it's just called ...         1
6464   when looking for apps to play on a long car ri...         1
2240   If you love Uno you will love this game. It al...         1
17921  ........love it........fun.......the bear is a...         1
18868  This is the worst app ever. It takes up 1/4 of...         0
15828  This is a great app. It never bugs out. Very w...         1
863    I had heard about this game and tried to see i...         0
5508   Wat an awesome game! I loved on my ipod but no...         1
4868   I love this calculator. It is the clearest and...         1
15200  Fun when your bored, or with friends. This ver...         1

In [36]:
#Osserviamo quali sono i nomi di colonna #

In [37]:
list(amazon.columns)

['reviewText', 'Positive']

In [38]:
#Il dataset è bilanciato, ovvero, il numero di recensioni positive è uguale a
#quello delle negative, oppure no?

In [39]:
pos=(amazon['Positive']==1).sum() #Filtro sulla colonna 'Positive' metto in una variabile e sommo i valori#
neg=(amazon['Positive']==0).sum()

In [40]:
print(f"Il numero delle recensioni positive sono : {pos} \nIl numero delle recensioni negative sono: {neg}\nIl DataFrame è sbilanciato su recensioni positive")

Il numero delle recensioni positive sono : 15233
Il numero delle recensioni negative sono: 4767
Il DataFrame è sbilanciato su recensioni positive

In [41]:
#Il dataset diabetes.csv raccoglie persone con diabete o meno, e il valore di
#diverse variabili fisiologiche dei pazienti.#

In [42]:
import pandas as pd
import os
print(os.getcwd())
filepath = "C:/Users/Giuseppe/3_PYTHON/FILE_ESERC_CSV/diabetes.csv"
diab = pd.read_csv(filepath)

C:\Users\Giuseppe\3_PYTHON

In [43]:
#Osserviamone le dimensioni e un'anteprima di cinque righe;#

In [44]:
diab.shape

(768, 9)

In [45]:
diab.head(5)

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [46]:
#Prendiamoci un po' di tempo per dare un'occhiata ai metadati delle colonne;#

In [47]:
list(diab.columns)

['Number of times pregnant',
 'Plasma glucose concentration a 2 hours in an oral glucose tolerance test',
 'Diastolic blood pressure (mm Hg)',
 'Triceps skin fold thickness (mm)',
 '2-Hour serum insulin (mu U/ml)',
 'Body mass index (weight in kg/(height in m)^2)',
 'Diabetes pedigree function',
 'Age (years)',
 'Class variable']

In [48]:
#Stampiamo dei descrittori statistici del dataset#

In [49]:
diab.describe()

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [50]:
#Selezioniamo i dati relativi a diverse fasce di età: <20, 20-30, 30-40, 40-50, >50;#

In [51]:
a=(diab['Age (years)'] <20)

In [52]:
b= (diab['Age (years)'] >=20) & (diab['Age (years)'] <30)

In [53]:
c= (diab['Age (years)'] >=30) & (diab['Age (years)'] <40)

In [54]:
d= (diab['Age (years)'] >=40) & (diab['Age (years)'] <50)

In [55]:
e= (diab['Age (years)'] >=50)

In [56]:
diab[b]

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age (years),Class variable
3,1,89,66,23,94,28.1,0.167,21,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
20,3,126,88,41,235,39.3,0.704,27,0
23,9,119,80,35,0,29.0,0.263,29,1
...,...,...,...,...,...,...,...,...,...
753,0,181,88,44,510,43.3,0.222,26,1
758,1,106,76,0,0,37.5,0.197,26,0
760,2,88,58,26,16,28.4,0.766,22,0
764,2,122,70,27,0,36.8,0.340,27,0
767,1,93,70,31,0,30.4,0.315,23,0

In [57]:
m1=(diab.loc[a,'Diastolic blood pressure (mm Hg)']).mean()
m2=(diab.loc[b,'Diastolic blood pressure (mm Hg)']).mean()
m3=(diab.loc[c,'Diastolic blood pressure (mm Hg)']).mean()
m4=(diab.loc[d,'Diastolic blood pressure (mm Hg)']).mean()
m5=(diab.loc[e,'Diastolic blood pressure (mm Hg)']).mean()
print(f"La media della pressione sanguigna per fasce d'età: \n<20      {m1}\n20<=<30  {m2}\n30<=<40  {m3}\n40<=<50  {m4}\n>50      {m5}")

La media della pressione sanguigna per fasce d'età:
<20      nan
20<=<30  65.34848484848484
30<=<40  69.66666666666667
40<=<50  73.94067796610169
>50      78.37078651685393

In [58]:
#Qual è la media della pressione per ogni singolo anno di età?#

In [59]:
y=diab.groupby('Age (years)')['Diastolic blood pressure (mm Hg)'].mean()

In [60]:
media_pressione_x_età = [y,'Diastolic blood pressure (mm Hg)']
print(media_pressione_x_età)

[Age (years)
21    65.936508
22    63.722222
23    64.315789
24    64.956522
25    59.666667
26    64.181818
27    73.500000
28    68.314286
29    68.241379
30    64.857143
31    64.375000
32    70.062500
33    65.647059
34    74.000000
35    75.600000
36    69.125000
37    75.947368
38    71.125000
39    72.666667
40    69.230769
41    67.590909
42    73.388889
43    78.461538
44    61.750000
45    83.066667
46    76.000000
47    78.333333
48    78.400000
49    81.400000
50    78.250000
51    84.500000
52    81.500000
53    79.000000
54    89.333333
55    70.250000
56    76.333333
57    76.800000
58    78.285714
59    74.000000
60    80.000000
61    76.000000
62    71.500000
63    78.000000
64    78.000000
65    78.666667
66    86.000000
67    72.666667
68    82.000000
69    81.000000
70    82.000000
72     0.000000
81    74.000000
Name: Diastolic blood pressure (mm Hg), dtype: float64, 'Diastolic blood pressure (mm Hg)']

In [61]:
filepath = "C:/Users/Giuseppe/3_PYTHON/FILE_ESERC_CSV/insurance.csv" 
insur = pd.read_csv(filepath)   #Ci siamo connessi alla tabella Insurance #

In [62]:
insur

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [63]:
insur.shape #Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna #

(1338, 7)

In [64]:
insur.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [65]:
insur.loc[:,'region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [66]:
a=insur.loc[:,'region']=='southwest'  #Creiamo un filtro per ogni Area geografice #
b=insur.loc[:,'region']=='southeast'
c=insur.loc[:,'region']=='northwest'
d=insur.loc[:,'region']=='northeast'

In [67]:
a1=(insur.loc[a,'charges']).mean()  #Calcoliamo la media di charges per ogni DataFrame risultante dal filtro #
b1=(insur.loc[b,'charges']).mean()
c1=(insur.loc[c,'charges']).mean()
d1=(insur.loc[d,'charges']).mean()

In [68]:
print(f"Media Charges per Area Geografica : \nsouthwest  {a1} \nsoutheast  {b1}\nnorthwest  {c1}\nnortheast  {d1}\n")

Media Charges per Area Geografica :
southwest  12346.937377292308
southeast  14735.411437609888
northwest  12417.57537396923
northeast  13406.384516385804

In [69]:
insur.groupby('region')['charges'].mean()

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

In [70]:
insur.groupby('smoker')['charges'].mean() #Possiamo fare la stessa cosa con il groupby#

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64

In [71]:
insur.groupby('sex')['charges'].mean()

sex
female    12569.578844
male      13956.751178
Name: charges, dtype: float64

In [72]:
insur['bmi'].describe() #Quali sono i descrittori statistici di bmi?#

count    1338.000000
mean       30.663397
std         6.098187
min        15.960000
25%        26.296250
50%        30.400000
75%        34.693750
max        53.130000
Name: bmi, dtype: float64

In [73]:
insur['bmi']

0       27.900
1       33.770
2       33.000
3       22.705
4       28.880
         ...
1333    30.970
1334    31.920
1335    36.850
1336    25.800
1337    29.070
Name: bmi, Length: 1338, dtype: float64

In [74]:
#Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi?#
#Si poteva anche fare un filtro per ogni quartile e vedere i valori statistici con la funzione .describe sulla colonna 'charges'

In [75]:
q1_media = insur[insur['bmi'] <= 26.296250]['charges'].mean()
q1_min = insur[insur['bmi'] <= 26.296250]['charges'].min()
q1_max = insur[insur['bmi'] <= 26.296250]['charges'].max()
print(f" 1° quartile BMI :\nmedia   {q1_media}\nminimo  {q1_min}\nmassimo {q1_max}")

 1° quartile BMI :
media   10360.662825492538
minimo  1121.8739
massimo 38245.59327

In [76]:
q2_media = insur[insur['bmi'] <= 30.400000]['charges'].mean()
q2_min = insur[insur['bmi'] <= 30.40000]['charges'].min()
q2_max = insur[insur['bmi'] <= 30.40000]['charges'].max()
print(f" 2° quartile BMI :\nmedia   {q2_media}\nminimo  {q2_min}\nmassimo {q2_max}")

 2° quartile BMI :
media   10886.581103445766
minimo  1121.8739
massimo 62592.87309

In [77]:
q3_media = insur[insur['bmi'] <= 34.693750]['charges'].mean()
q3_min = insur[insur['bmi'] <= 34.693750]['charges'].min()
q3_max = insur[insur['bmi'] <= 34.693750]['charges'].max()
print(f" 3° quartile BMI :\nmedia   {q3_media}\nminimo  {q3_min}\nmassimo {q3_max}")

 3° quartile BMI :
media   12028.77985970987
minimo  1121.8739
massimo 62592.87309

In [78]:
q4_media = insur[insur['bmi'] > 34.693750]['charges'].mean()
q4_min = insur[insur['bmi'] > 34.693750]['charges'].min()
q4_max = insur[insur['bmi'] > 34.693750]['charges'].max()
print(f" 4° quartile BMI :\nmedia   {q4_media}\nminimo  {q4_min}\nmassimo {q4_max}")

 4° quartile BMI :
media   16987.936690955226
minimo  1141.4451
massimo 63770.42801

In [79]:
filepath = "C:/Users/Giuseppe/3_PYTHON/FILE_ESERC_CSV/pokemon.csv" 
pok = pd.read_csv(filepath)   #Ci siamo connessi alfile csv Pokemon #

In [80]:
pok

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [81]:
pok.shape

(800, 13)

In [82]:
pok.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [83]:
#È verosimile che la prima colonna dovrebbe essere un indice # I numeri nella colonna '#' sono meno delle 800 righe della tabella #
# per cui o per alcune righe si ripetono i valori o in alcune righe manca il valore ... può assolvere alla funzione di indice ma si dovrebbe#
#capire se ci sono valori che si ripetono e perchè#

In [84]:
pok=pok.set_index('#')

In [85]:
pok

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [86]:
pok.iloc[:,0].value_counts()

Name
Bulbasaur              1
Uxie                   1
GalladeMega Gallade    1
Probopass              1
Dusknoir               1
                      ..
Lugia                  1
Ho-oh                  1
Celebi                 1
Treecko                1
Volcanion              1
Name: count, Length: 800, dtype: int64

In [87]:
#Quali sono i Pokémon leggendari?#

In [88]:
Leg=pok[pok['Legendary']==True]

In [91]:
print(Leg['Name'])

#
144               Articuno
145                 Zapdos
146                Moltres
150                 Mewtwo
150    MewtwoMega Mewtwo X
              ...
719                Diancie
719    DiancieMega Diancie
720    HoopaHoopa Confined
720     HoopaHoopa Unbound
721              Volcanion
Name: Name, Length: 65, dtype: object

In [92]:
Typ=pok[pok['Type 1']=='Grass']

In [93]:
print(Typ['Name'])

#
1                  Bulbasaur
2                    Ivysaur
3                   Venusaur
3      VenusaurMega Venusaur
43                    Oddish
               ...
650                  Chespin
651                Quilladin
652               Chesnaught
672                   Skiddo
673                   Gogoat
Name: Name, Length: 70, dtype: object

In [105]:
F2=(pok['Legendary']==True) & (pok['Type 1']=='Grass') #E quali sono i leggendari di tipo 1 Grass?#
pok_F2=pok[F2]
pok_F2

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
492,ShayminLand Forme,Grass,NaN,600,100,100,100,100,100,100,4,True
492,ShayminSky Forme,Grass,Flying,600,100,103,75,120,75,127,4,True
640,Virizion,Grass,Fighting,580,91,90,72,90,129,108,5,True

In [106]:
F3=(pok['Legendary']==True) & (pok['Type 1']=='Ice') #E leggendari di tipo 1 Ice ?
pok_F3=pok[F3]
pok_F3

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
378,Regice,Ice,NaN,580,80,50,100,100,200,50,3,True

In [107]:
F4=(pok['Legendary']==True) & (pok['Type 1']=='Fire') #E leggendari di tipo 1 Fire?
pok_F4=pok[F4]
pok_F4

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,True
250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,True
485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [113]:
pok_ord=pok.sort_values(by='Name', ascending=True)  #Ordiniamo il dataset per la colonna Name#
pok_ord

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [114]:
pok_ord=pok_ord.set_index('Name') #Trasformiamo Name nell'indice;#
pok_ord

,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...
Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

In [115]:
F4=(pok['HP']>50) & (pok['HP']<=60) #E leggendari di tipo 1 Ice ?
pok_F4=pok[F4]
pok_F4

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
707,Klefki,Steel,Fairy,470,57,80,91,80,87,75,6,False
710,PumpkabooLarge Size,Ghost,Grass,335,54,66,70,44,55,46,6,False
710,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False
711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False

In [121]:
pok_F4_ordinato = pok_F4.sort_values(by='HP')  #per una maggiore visibilità si ordina

In [122]:
pok_F4_ordinato

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
583,Vanillish,Ice,NaN,395,51,65,65,80,75,59,5,False
633,Deino,Dark,Dragon,300,52,65,50,45,50,38,5,False
83,Farfetch'd,Normal,Flying,352,52,65,55,58,62,60,1,False
686,Inkay,Dark,Psychic,288,53,54,53,37,46,45,6,False
393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...
411,Bastiodon,Rock,Steel,495,60,52,168,47,138,30,4,False
407,Roserade,Grass,Poison,515,60,70,65,125,105,90,4,False
404,Luxio,Electric,NaN,363,60,85,49,60,49,60,4,False
101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False